export type ConstructionAuditScoreBand = 'excellent' | 'good' | 'fair' | 'needs_attention' | 'missing' | 'unknown';

export type PublicWorksConstructionAuditRecord = {
  id: string;
  module: 'public_works_construction_audit_records';
  resourceName: string;
  resourceQuarterRaw?: string;
  resourceRocYear?: number;
  resourceYear?: number;
  resourceQuarter?: 1 | 2 | 3 | 4;
  resourceQuarterKey?: string;
  sourceSequenceNumber?: number;
  projectName: string;
  projectNameNormalized?: string;
  responsibleAgency?: string;
  responsibleAgencyNormalized?: string;
  contractAmountThousandNtd?: number;
  contractAmountNtd?: number;
  designUnit?: string;
  designUnitNormalized?: string;
  supervisionUnit?: string;
  supervisionUnitNormalized?: string;
  contractor?: string;
  contractorNormalized?: string;
  projectManagementUnit?: string;
  projectManagementUnitNormalized?: string;
  auditDateRaw?: string;
  auditDate?: string;
  auditYear?: number;
  auditMonth?: number;
  auditMonthKey?: string;
  auditQuarter?: string;
  notificationMethod?: string;
  notificationMethodNormalized?: string;
  auditScore?: number;
  auditScoreBand: ConstructionAuditScoreBand;
  contractorDeductionPoints?: number;
  supervisionDeductionPoints?: number;
  pcmDeductionPoints?: number;
  totalDeductionPoints?: number;
  hasContractorDeductionPoints: boolean;
  hasSupervisionDeductionPoints: boolean;
  hasPcmDeductionPoints: boolean;
  notes?: string;
  hasNotes: boolean;
  possibleProjectLocationText?: string;
  possibleDistrict?: string;
  sourceRecordHash: string;
  source: '臺北市政府施工查核情形一覽表';
  sourceAgency: '臺北市政府工務局';
};

export type PublicWorksConstructionAuditSummary = {
  totalRecords: number;
  minAuditDate?: string;
  maxAuditDate?: string;
  latestAuditQuarter?: string;
  uniqueProjectCount: number;
  responsibleAgencyCount: number;
  contractorCount: number;
  designUnitCount: number;
  supervisionUnitCount: number;
  projectManagementUnitCount: number;
  recordsWithAuditScore: number;
  recordsWithContractAmount: number;
  recordsWithDeductionPoints: number;
  recordsWithNotes: number;
  totalContractAmountThousandNtd?: number;
  averageContractAmountThousandNtd?: number;
  averageAuditScore?: number;
  medianAuditScore?: number;
  totalContractorDeductionPoints?: number;
  totalSupervisionDeductionPoints?: number;
  totalPcmDeductionPoints?: number;
  totalDeductionPoints?: number;
  byAuditQuarter: Array<{ auditQuarter: string; recordCount: number; averageAuditScore?: number; totalContractAmountThousandNtd?: number; totalDeductionPoints?: number }>;
  byResponsibleAgency: Array<{ responsibleAgency: string; recordCount: number; averageAuditScore?: number; totalContractAmountThousandNtd?: number; totalDeductionPoints?: number }>;
  byContractor: Array<{ contractor: string; recordCount: number; averageAuditScore?: number; totalContractAmountThousandNtd?: number; totalDeductionPoints?: number }>;
  byScoreBand: Array<{ auditScoreBand: ConstructionAuditScoreBand; count: number }>;
  byNotificationMethod: Array<{ notificationMethod: string; count: number }>;
};
