export type StopWorkReasonCategory = 'fall_prevention' | 'scaffold' | 'opening_or_edge' | 'electrical' | 'lifting_equipment' | 'excavation' | 'fire_or_hot_work' | 'machinery' | 'protective_equipment' | 'other' | 'unknown';
export type StopWorkScopeCategory = 'entire_site' | 'scaffold' | 'exterior_wall' | 'opening_or_edge' | 'floor_or_area' | 'equipment' | 'other' | 'unknown';

export type ConstructionStopResumeWorkRecord = {
  id: string;
  module: 'construction_stop_resume_work_records';
  sourceSequenceNumber?: number;
  projectName: string;
  projectNameNormalized?: string;
  businessEntityName: string;
  businessEntityNameNormalized?: string;
  stopWorkDateRaw?: string;
  stopWorkDate?: string;
  stopWorkYear?: number;
  stopWorkMonth?: number;
  stopWorkMonthKey?: string;
  stopWorkQuarter?: string;
  resumeOrReviewDateRaw?: string;
  resumeOrReviewDate?: string;
  resumeOrReviewYear?: number;
  resumeOrReviewMonth?: number;
  resumeOrReviewMonthKey?: string;
  resumeOrReviewQuarter?: string;
  daysUntilResumeOrReview?: number;
  hasResumeOrReviewDate: boolean;
  isMissingResumeOrReviewDate: boolean;
  stopWorkScope?: string;
  stopWorkScopeNormalized?: string;
  stopWorkScopeCategory: StopWorkScopeCategory;
  stopWorkReason?: string;
  stopWorkReasonNormalized?: string;
  stopWorkReasonCategory: StopWorkReasonCategory;
  hasFallPreventionKeyword: boolean;
  hasScaffoldKeyword: boolean;
  hasOpeningEdgeKeyword: boolean;
  hasElectricalKeyword: boolean;
  hasLiftingEquipmentKeyword: boolean;
  hasExcavationKeyword: boolean;
  possibleDistrict?: string;
  sourceRecordHash: string;
  source: '臺北市停復工公開資訊';
  sourceAgency: '臺北市政府勞動局勞動檢查處';
};

export type ConstructionStopResumeWorkSummary = {
  totalRecords: number;
  minStopWorkDate?: string;
  maxStopWorkDate?: string;
  latestStopWorkMonth?: string;
  uniqueProjectCount: number;
  uniqueBusinessEntityCount: number;
  recordsWithResumeOrReviewDate: number;
  recordsMissingResumeOrReviewDate: number;
  averageDaysUntilResumeOrReview?: number;
  medianDaysUntilResumeOrReview?: number;
  maxDaysUntilResumeOrReview?: number;
  byStopWorkMonth: Array<{ stopWorkMonthKey: string; recordCount: number; missingResumeOrReviewDateCount: number; averageDaysUntilResumeOrReview?: number }>;
  byStopWorkQuarter: Array<{ stopWorkQuarter: string; recordCount: number; missingResumeOrReviewDateCount: number; averageDaysUntilResumeOrReview?: number }>;
  byBusinessEntity: Array<{ businessEntityName: string; recordCount: number; uniqueProjectCount: number; missingResumeOrReviewDateCount: number; averageDaysUntilResumeOrReview?: number }>;
  byProject: Array<{ projectName: string; recordCount: number; businessEntityName?: string; firstStopWorkDate?: string; latestStopWorkDate?: string; missingResumeOrReviewDateCount: number }>;
  byStopWorkReasonCategory: Array<{ stopWorkReasonCategory: StopWorkReasonCategory; count: number }>;
  byStopWorkScopeCategory: Array<{ stopWorkScopeCategory: StopWorkScopeCategory; count: number }>;
  topReasonKeywords: Array<{ keyword: string; count: number }>;
  topScopeKeywords: Array<{ keyword: string; count: number }>;
};
